### ISSUE TITLE
two snapshot with the same name

### ISSUE THREAD

**Issue by isbkch** [dergachev/vagrant-vbox-snapshot#37]
Hi,
Listing the snapshots show 2 with the same name (Let's not dwell on how that happened). I have

Name: latest (UUID: xxxx-xxx-xxxx....)
Name: latest (UUID: yyy-yyy-yyyyy....)

The UUID are of course different so I was wondering how could I load one of those snapshots via UUID because doing "vagrant snapshot go latest" loads always the first one

**Comment by isbkch** [comment]
I actually figure it out. I used the UUID instead of the name to load the snapshot and it worked.

**Comment by dergachev** [comment]
Happy to hear that! Thanks for using the plugin.
